create database project;
use project;
CREATE TABLE CUSTOMERS(
    CUSTOMER_ID int PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    COUNTRY VARCHAR(20)
);
CREATE TABLE PRODUCTS(
    PRODUCT_ID int PRIMARY KEY,
    PRODUCT_NAME VARCHAR(30),
    CATEGORY VARCHAR(20),
    PRICE decimal(8,2)
);

CREATE TABLE ORDERS(
    ORDER_ID int PRIMARY KEY,
    CUSTOMER_ID int,
    PRODUCT_ID int,
    ORDER_DATE DATE,
    QUANTITY int,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

INSERT INTO CUSTOMERS VALUES(101,'RAHUL','HYDERABAD','INDIA');
INSERT INTO CUSTOMERS VALUES(102,'PRIYA','VIJAYAWADA','INDIA');
INSERT INTO CUSTOMERS VALUES(103,'ARJUN','CHENNAI','INDIA');
INSERT INTO CUSTOMERS VALUES(104,'NEHA','MUMBAI','INDIA');
INSERT INTO CUSTOMERS VALUES(105,'KIRAN','NEW YORK','USA');
INSERT INTO CUSTOMERS VALUES(106,'SNEHA','LONDON','UK');
INSERT INTO PRODUCTS VALUES(1,'LAPTOP','ELECTRONICS',50000);
INSERT INTO PRODUCTS VALUES(2,'MOBILE','ELECTRONICS',25000);
INSERT INTO PRODUCTS VALUES(3,'HEADPHONES','ELECTRONICS',3000);
INSERT INTO PRODUCTS VALUES(4,'WATCH','ACCESSORIES',5000);
INSERT INTO PRODUCTS VALUES(5,'SHOES','FASHION',2500);
INSERT INTO PRODUCTS VALUES(6,'BAG','FASHION',1500);


INSERT INTO ORDERS VALUES(1001,101,1,'01-JAN-25',1);
INSERT INTO ORDERS VALUES(1002,102,2,'02-JAN-25',1);
INSERT INTO ORDERS VALUES(1003,103,3,'03-JAN-25',2);
INSERT INTO ORDERS VALUES(1004,104,4,'04-JAN-25',1);
INSERT INTO ORDERS VALUES(1005,105,5,'05-JAN-25',3);
INSERT INTO ORDERS VALUES(1006,106,6,'06-JAN-25',2);

INSERT INTO ORDERS VALUES(1007,101,2,'07-JAN-25',1);
INSERT INTO ORDERS VALUES(1008,102,1,'08-JAN-25',1);
INSERT INTO ORDERS VALUES(1009,103,4,'09-JAN-25',2);
INSERT INTO ORDERS VALUES(1010,104,5,'10-JAN-25',1);
INSERT INTO ORDERS VALUES(1011,105,3,'11-JAN-25',2);
INSERT INTO ORDERS VALUES(1012,106,2,'12-JAN-25',1);

INSERT INTO ORDERS VALUES(1013,101,6,'13-JAN-25',3);
INSERT INTO ORDERS VALUES(1014,102,5,'14-JAN-25',2);
INSERT INTO ORDERS VALUES(1015,103,1,'15-JAN-25',1);
INSERT INTO ORDERS VALUES(1016,104,2,'16-JAN-25',2);
INSERT INTO ORDERS VALUES(1017,105,4,'17-JAN-25',1);
INSERT INTO ORDERS VALUES(1018,106,3,'18-JAN-25',4);

select * from products;
select * from orders;
select * from CUSTOMERS;

SELECT CUSTOMER_NAME FROM CUSTOMERS;
SELECT PRODUCT_NAME,PRICE FROM PRODUCTS;

 SELECT * FROM products WHERE PRICE>5000;

 SELECT CITY FROM CUSTOMERS;
 SELECT * FROM ORDERS WHERE QUANTITY >2;

 SELECT MAX(PRICE) FROM PRODUCTS;


 SELECT COUNT(*) FROM CUSTOMERS;

 SELECT CUSTOMER_NAME,CITY FROM CUSTOMERS;
 
 SELECT * FROM CUSTOMERS WHERE COUNTRY='INDIA';

SELECT * FROM ORDERS WHERE QUANTITY>2;

SELECT COUNT(*) FROM CUSTOMERS;

SELECT MAX(PRICE) FROM PRODUCTS;


SELECT AVG(PRICE) FROM PRODUCTS;

SELECT SUM(QUANTITY) FROM ORDERS;

SELECT SUM(PRICE*QUANTITY) REVENUE FROM ORDERS JOIN PRODUCTS ON ORDERS.PRODUCT_ID=PRODUCTS.PRODUCT_ID;

---GROUP BY --
SELECT COUNT(*) NOF_ORDERS,CUSTOMERS.CUSTOMER_ID  FROM ORDERS JOIN CUSTOMERS ON 
ORDERS.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID  GROUP BY  CUSTOMERS.CUSTOMER_ID ;

SELECT SUM(QUANTITY) Quantity,C.CUSTOMER_NAME FROM CUSTOMERS C JOIN ORDERS O ON 
C.CUSTOMER_ID=O.CUSTOMER_ID GROUP BY C.CUSTOMER_NAME;

SELECT SUM(PRICE*QUANTITY) revenue,P.PRODUCT_ID FROM PRODUCTS P JOIN ORDERS O 
ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY P.PRODUCT_ID;

SELECT SUM(PRICE*QUANTITY)revenue,P.CATEGORY FROM  PRODUCTS P JOIN ORDERS O 
ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY P.CATEGORY;

SELECT COUNT(*),P.CATEGORY FROM  PRODUCTS P  GROUP BY P.CATEGORY;

SELECT AVG(PRICE),CATEGORY FROM PRODUCTS  GROUP BY CATEGORY;

SELECT C.CUSTOMER_NAME,COUNT(O.ORDER_ID)  FROM CUSTOMERS C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID GROUP BY C.CUSTOMER_NAME HAVING COUNT(*)>2;

SELECT COUNT(ORDER_ID),CUSTOMER_ID FROM ORDERS GROUP BY CUSTOMER_ID;

SELECT COUNT(QUANTITY),CUSTOMER_ID FROM ORDERS GROUP BY CUSTOMER_ID;

SELECT SUM(P.PRICE*O.QUANTITY) REVENUE,P.PRODUCT_ID FROM PRODUCTS P JOIN ORDERS O
ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY P.PRODUCT_ID;

SELECT AVG(QUANTITY) AVG_QUANTITY,P.PRODUCT_ID FROM PRODUCTS P JOIN ORDERS O 
ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY P.PRODUCT_ID;

SELECT SUM(PRICE*QUANTITY) REVENUE,CATEGORY FROM  
PRODUCTS JOIN ORDERS ON
PRODUCTS.PRODUCT_ID=ORDERS.PRODUCT_ID GROUP BY PRODUCTS.CATEGORY;

SELECT COUNT(*),CATEGORY FROM 
PRODUCTS GROUP BY CATEGORY;

SELECT COUNT(*),CUSTOMERS.CUSTOMER_ID FROM CUSTOMERS 
JOIN ORDERS ON CUSTOMERS.CUSTOMER_ID=ORDERS.CUSTOMER_ID
GROUP BY CUSTOMERS.CUSTOMER_ID HAVING COUNT(*)>2;

SELECT SUM(PRICE*QUANTITY) REVENUE ,PRODUCTS.PRODUCT_ID 
FROM PRODUCTS JOIN ORDERS ON PRODUCTS.PRODUCT_ID=ORDERS.PRODUCT_ID
GROUP BY PRODUCTS.PRODUCT_ID HAVING SUM(PRICE*QUANTITY)>20000;

SELECT COUNT(PRODUCT_ID),CATEGORY FROM PRODUCTS GROUP BY CATEGORY
HAVING COUNT(*)>0;

SELECT C.CUSTOMER_NAME,P.PRODUCT_NAME FROM
CUSTOMERS C JOIN ORDERS O ON 
C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON O.PRODUCT_ID=P.PRODUCT_ID;

SELECT C.CUSTOMER_NAME,P.PRODUCT_NAME,O.QUANTITY FROM 
CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN PRODUCTS P ON P.PRODUCT_ID =O.PRODUCT_ID;

SELECT C.CUSTOMER_NAME,P.PRODUCT_NAME,O.ORDER_DATE FROM
CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID;

SELECT C.CUSTOMER_NAME,SUM(PRICE*QUANTITY) FROM CUSTOMERS C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY C.CUSTOMER_NAME HAVING SUM(PRICE*QUANTITY) > AVG(PRICE*QUANTITY);

SELECT SUM(P.PRICE*O.QUANTITY),C.CUSTOMER_ID FROM CUSTOMERS C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID 
GROUP BY C.CUSTOMER_ID  HAVING SUM(P.PRICE*O.QUANTITY) > ALL (SELECT AVG(SPENDING) FROM (SELECT  SUM(P.PRICE*O.QUANTITY)
SPENDING FROM PRODUCTS P JOIN ORDERS O ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY O.CUSTOMER_ID)X );

SELECT C.CUSTOMER_NAME,
       SUM(P.PRICE * O.QUANTITY) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN PRODUCTS P
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING SUM(P.PRICE * O.QUANTITY) >
(
    SELECT AVG(SPENDING)
    FROM
    (
        SELECT SUM(P.PRICE * O.QUANTITY) AS SPENDING
        FROM PRODUCTS P
        JOIN ORDERS O
            ON P.PRODUCT_ID = O.PRODUCT_ID
        GROUP BY O.CUSTOMER_ID
    ) X
);


SELECT C.CUSTOMER_NAME,SUM(P.PRICE*O.QUANTITY) AS SPENDINGS,DENSE_RANK() OVER(ORDER BY SUM(P.PRICE*O.QUANTITY) DESC) DR FROM CUSTOMERS C JOIN 
ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY C.CUSTOMER_NAME ;
 
 SELECT * FROM (SELECT CUSTOMER_NAME,SPENDINGS, DENSE_RANK()OVER (ORDER BY SPENDINGS DESC) AS DR
 FROM (
 SELECT C.CUSTOMER_NAME,SUM(P.PRICE*O.QUANTITY) AS SPENDINGS FROM CUSTOMERS C JOIN 
 ORDERS O  ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON O.PRODUCT_ID=P.PRODUCT_ID
 GROUP BY C.CUSTOMER_NAME)X )Y WHERE DR=1;

 SELECT * FROM (SELECT CUSTOMER_NAME,SPENDINGS, DENSE_RANK()OVER (ORDER BY SPENDINGS DESC) AS DR
 FROM (
 SELECT C.CUSTOMER_NAME,SUM(P.PRICE*O.QUANTITY) AS SPENDINGS FROM CUSTOMERS C JOIN 
 ORDERS O  ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON O.PRODUCT_ID=P.PRODUCT_ID
 GROUP BY C.CUSTOMER_NAME)X )Y WHERE DR=2;
 

 SELECT P.PRODUCT_ID,SUM(P.PRICE*O.QUANTITY) SPENDINGS FROM CUSTOMERS C JOIN
 ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID
 GROUP BY P.PRODUCT_ID HAVING SUM(P.PRICE*O.QUANTITY) > (SELECT AVG(SPENDINGS) FROM   
  (SELECT SUM(P.PRICE *O.QUANTITY) SPENDINGS,P.PRODUCT_ID FROM PRODUCTS P JOIN 
  ORDERS O ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY P.PRODUCT_ID) X );

  SELECT P.CATEGORY,SUM(P.PRICE*O.QUANTITY) SPENDINGS FROM CUSTOMERS C JOIN 
  ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID
  GROUP BY P.CATEGORY HAVING SUM(P.PRICE*O.QUANTITY) =(SELECT MAX(SPENDINGS) FROM
  (SELECT P.CATEGORY,SUM(P.PRICE*O.QUANTITY) SPENDINGS FROM CUSTOMERS C JOIN 
  ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID
  GROUP BY P.CATEGORY)X );


SELECT P.PRODUCT_NAME,SUM(P.PRICE*O.QUANTITY) AS REVENUE,(SUM(P.PRICE*O.QUANTITY)*100/
(SELECT SUM(P1.PRICE*O1.QUANTITY) FROM PRODUCTS P1 JOIN ORDERS O1 ON
P1.PRODUCT_ID=O1.PRODUCT_ID) ) AS PERCENTAGE FROM PRODUCTS P JOIN ORDERS O ON P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY P.PRODUCT_NAME;

SELECT P.CATEGORY,SUM(P.PRICE*O.QUANTITY) AS REVENUE,(SUM(P.PRICE*O.QUANTITY)*100/
(SELECT SUM(P1.PRICE*O1.QUANTITY) FROM PRODUCTS P1 JOIN ORDERS O1 ON
P1.PRODUCT_ID=O1.PRODUCT_ID) ) AS PERCENTAGE FROM PRODUCTS P JOIN ORDERS O ON P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY P.CATEGORY;


SELECT * FROM 
(SELECT C.CUSTOMER_NAME,SUM(P.PRICE*O.QUANTITY) REVENUE,RANK()OVER(ORDER BY SUM(P.PRICE*O.QUANTITY) DESC) DR 
FROM CUSTOMERS C JOIN ORDERS O ON  C.CUSTOMER_ID=O.CUSTOMER_ID JOIN
PRODUCTS P  ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY C.CUSTOMER_NAME)X;

SELECT * FROM (SELECT P.PRODUCT_NAME,SUM(P.PRICE*O.QUANTITY)REVENUE,DENSE_RANK()
OVER(ORDER BY SUM(P.PRICE*O.QUANTITY) DESC) DR FROM PRODUCTS P JOIN ORDERS O 
ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY P.PRODUCT_NAME)X;

SELECT * FROM (SELECT P.PRODUCT_NAME,SUM(P.PRICE*O.QUANTITY)REVEUNE,
DENSE_RANK()OVER(ORDER BY SUM(P.PRICE*O.QUANTITY) DESC) DR FROM PRODUCTS P
JOIN ORDERS O ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY P.PRODUCT_NAME)X WHERE DR=2;

SELECT * FROM(SELECT C.CUSTOMER_NAME,SUM(P.PRICE*O.QUANTITY)REVENUE,
DENSE_RANK()OVER(ORDER BY SUM(P.PRICE*O.QUANTITY)DESC) DR FROM 
CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY C.CUSTOMER_NAME)X
WHERE DR<=3;

SELECT * FROM(SELECT P.PRODUCT_NAME,P.CATEGORY,SUM(P.PRICE*O.QUANTITY)REVENUE,
DENSE_RANK()OVER(ORDER BY SUM(P.PRICE*O.QUANTITY)DESC) DR FROM 
CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY P.PRODUCT_NAME,P.CATEGORY)X
WHERE DR<=3;

SELECT O.ORDER_ID,P.PRODUCT_NAME,O.QUANTITY,LAG(O.QUANTITY)OVER(ORDER BY O.ORDER_ID DESC) 
FROM ORDERS O JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID; 


SELECT O.ORDER_ID,P.PRODUCT_NAME,O.QUANTITY,LEAD(O.QUANTITY)OVER(ORDER BY O.ORDER_ID DESC) DR
FROM ORDERS O JOIN PRODUCTS P ON P.PRODUCT_ID=O.PRODUCT_ID;

SELECT PRODUCTS.*,CASE WHEN PRICE>20000 THEN 'EXPENSIVE'
WHEN PRICE>10000 THEN 'MEDIUM'
ELSE 'LOW COST'
END AS RESULT FROM PRODUCTS;

SELECT C.CUSTOMER_NAME,CASE WHEN SUM(P.PRICE*O.QUANTITY)>50000 THEN 'PREMIUM'
WHEN SUM(P.PRICE*O.QUANTITY)>20000 THEN 'GOLD'
ELSE 'REGULAR'
END AS RESULT FROM CUSTOMERS C ,PRODUCTS P ,ORDERS O WHERE 
C.CUSTOMER_ID=O.CUSTOMER_ID AND P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY C.CUSTOMER_NAME;

SELECT * FROM (SELECT MAX(PRICE) EXPENSIVE FROM PRODUCTS JOIN ORDERS 
ON PRODUCTS.PRODUCT_ID=ORDERS.PRODUCT_ID JOIN CUSTOMERS C  ON ORDERS.CUSTOMER_ID=C.CUSTOMER_ID)X;

SELECT P.PRODUCT_NAME FROM PRODUCTS P WHERE P.PRICE > 
(SELECT AVG(P1.PRICE) FROM PRODUCTS P1 WHERE P1.CATEGORY=P.CATEGORY);


SELECT C.CUSTOMER_NAME,SUM(P.PRICE*O.QUANTITY) FROM PRODUCTS P JOIN ORDERS O 
ON P.PRODUCT_ID=O.PRODUCT_ID JOIN CUSTOMERS C ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME HAVING SUM(P.PRICE*O.QUANTITY) >(SELECT SUM(P1.PRICE*O1.QUANTITY)
FROM PRODUCTS P1 JOIN ORDERS O1 ON P1.PRODUCT_ID=O1.PRODUCT_ID JOIN CUSTOMERS C1 ON
C1.CUSTOMER_ID=O1.CUSTOMER_ID WHERE C1.CUSTOMER_NAME='RAHUL');

SELECT C.CUSTOMER_NAME,SUM(P.PRICE*O.QUANTITY) FROM PRODUCTS P JOIN ORDERS O 
ON P.PRODUCT_ID=O.PRODUCT_ID JOIN CUSTOMERS C ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME HAVING SUM(P.PRICE*O.QUANTITY)>(SELECT SUM(P1.PRICE*O1.QUANTITY)
FROM PRODUCTS P1 JOIN ORDERS O1 ON P1.PRODUCT_ID=O1.PRODUCT_ID JOIN CUSTOMERS C1 ON
C1.CUSTOMER_ID=O1.CUSTOMER_ID WHERE C1.COUNTRY='INDIA');


SELECT SUM(P1.PRICE*O1.QUANTITY)
FROM PRODUCTS P1
JOIN ORDERS O1
ON P1.PRODUCT_ID=O1.PRODUCT_ID
JOIN CUSTOMERS C1
ON C1.CUSTOMER_ID=O1.CUSTOMER_ID
WHERE C1.COUNTRY='INDIA';

SELECT P.PRODUCT_NAME FROM PRODUCTS P  WHERE P.PRODUCT_ID NOT IN (SELECT O.PRODUCT_ID FROM ORDERS O  JOIN 
CUSTOMERS C ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE  C.CUSTOMER_NAME='RAHUL');

SELECT P.CATEGORY,MAX(P.PRICE) FROM PRODUCTS P GROUP BY P.CATEGORY;

SELECT P.CATEGORY,P.PRODUCT_NAME,P.PRICE FROM PRODUCTS P WHERE P.PRICE =(
SELECT MAX(P1.PRICE) FROM PRODUCTS P1 WHERE P1.CATEGORY=P.CATEGORY);

SELECT C.CUSTOMER_NAME,C.COUNTRY,SUM(P.PRICE*O.QUANTITY) FROM
  PRODUCTS P JOIN ORDERS O 
ON P.PRODUCT_ID=O.PRODUCT_ID JOIN CUSTOMERS C ON C.CUSTOMER_ID =O.CUSTOMER_ID GROUP BY 
C.CUSTOMER_NAME,C.COUNTRY HAVING SUM(P.PRICE*O.QUANTITY)>
(SELECT AVG(SPENDINGS) FROM 
(SELECT SUM(P1.PRICE*O1.QUANTITY) SPENDINGS,C1.CUSTOMER_ID  FROM PRODUCTS P1 JOIN ORDERS O1 
ON P1.PRODUCT_ID=O1.PRODUCT_ID JOIN CUSTOMERS C1 ON O1.CUSTOMER_ID=C1.CUSTOMER_ID 
WHERE C1.COUNTRY='INDIA' GROUP BY C1.CUSTOMER_ID)X 
);


SELECT P.PRODUCT_NAME,SUM(P.PRICE*O.QUANTITY) FROM PRODUCTS P JOIN ORDERS O 
ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY P.PRODUCT_NAME HAVING SUM(P.PRICE*O.QUANTITY) >
(SELECT AVG(SPENDINGS) FROM 
(SELECT P1.CATEGORY,SUM(P1.PRICE*O1.QUANTITY) SPENDINGS FROM PRODUCTS P1 JOIN
ORDERS O1 ON P1.PRODUCT_ID=O1.PRODUCT_ID GROUP BY P1.CATEGORY)X);

SELECT COUNT( P.PRODUCT_ID),P.CATEGORY 
FROM PRODUCTS P  GROUP BY P.CATEGORY HAVING COUNT(*)>1;

SELECT C.CUSTOMER_NAME,COUNT(P.CATEGORY)  FROM CUSTOMERS C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID join PRODUCTS P ON 
P.PRODUCT_ID=O.PRODUCT_ID GROUP BY C.CUSTOMER_NAME HAVING COUNT(DISTINCT P.CATEGORY)>1;

SELECT C.CUSTOMER_ID,COUNT(DISTINCT P.CATEGORY) FROM CUSTOMERS C JOIN ORDERS O 
ON  C.CUSTOMER_ID=O.CUSTOMER_ID JOIN  PRODUCTS P 
ON P.PRODUCT_ID=O.PRODUCT_ID GROUP BY C.CUSTOMER_ID HAVING COUNT(DISTINCT P.CATEGORY)=
(SELECT COUNT(DISTINCT P1.CATEGORY) FROM PRODUCTS P1);

SELECT C.CUSTOMER_NAME FROM CUSTOMERS C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P ON
P.PRODUCT_ID=O.PRODUCT_ID WHERE P.CATEGORY IN('ELECTRONICS','FASHION');


SELECT C1.CUSTOMER_NAME,C2.CUSTOMER_NAME,O1.PRODUCT_ID FROM
ORDERS O1 JOIN ORDERS O2 ON
O1.PRODUCT_ID=O2.PRODUCT_ID
JOIN CUSTOMERS C1
ON C1.CUSTOMER_ID=O1.CUSTOMER_ID
JOIN CUSTOMERS C2
ON C2.CUSTOMER_ID=O2.CUSTOMER_ID;

SELECT P.PRODUCT_NAME FROM PRODUCTS P JOIN
ORDERS O ON P.PRODUCT_ID=O.PRODUCT_ID 
JOIN CUSTOMERS C ON  C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE C.CUSTOMER_NAME IN ('RAHUL','PRIYA')
GROUP BY P.PRODUCT_NAME HAVING COUNT(DISTINCT C.CUSTOMER_NAME)=2;


SELECT * FROM (
SELECT C.CUSTOMER_NAME,SUM(P.PRICE*O.QUANTITY)*100/
(SELECT SUM(P1.PRICE*O1.QUANTITY)FROM PRODUCTS P1 JOIN ORDERS O1
ON P1.PRODUCT_ID=O1.PRODUCT_ID ) PERCENTAGE,
DENSE_RANK() OVER (ORDER BY SUM(P.PRICE*O.QUANTITY) DESC) DR
FROM  CUSTOMERS C  JOIN ORDERS O ON C.CUSTOMER_ID=
O.CUSTOMER_ID JOIN PRODUCTS P  ON O.PRODUCT_ID = P.PRODUCT_ID 
GROUP BY C.CUSTOMER_NAME)X WHERE DR=1;


SELECT * FROM (
SELECT C.COUNTRY,C.CUSTOMER_NAME,SUM(P.PRICE*O.QUANTITY) SPENDINGS,
DENSE_RANK() OVER (
ORDER BY SUM(P.PRICE*O.QUANTITY) DESC )DR 
FROM CUSTOMERS C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID 
JOIN PRODUCTS P ON 
P.PRODUCT_ID=O.PRODUCT_ID GROUP BY C.CUSTOMER_NAME,C.COUNTRY)X
WHERE DR=1;

SELECT MONTH(O.ORDER_DATE) MONTH_DA,SUM(P.PRICE*O.QUANTITY) REVENUE
 FROM ORDERS O JOIN PRODUCTS P ON O.PRODUCT_ID=P.PRODUCT_ID
 GROUP BY MONTH(O.ORDER_DATE);

 SELECT C.CUSTOMER_NAME,COUNT(DISTINCT P.PRODUCT_ID) FROM CUSTOMERS C JOIN
 ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN PRODUCTS P 
 ON P.PRODUCT_ID=O.PRODUCT_ID WHERE P.CATEGORY='ELECTRONICS'
 GROUP BY C.CUSTOMER_NAME;
 
